develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35737:35729"
  container_name: gfw-umd-forest-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_APIKEY: <apikey>
    CARTODB_USER: <user>
    EE_PRIVATE_KEY: <key>
  command: develop
  volumes:
    - ./app:/opt/gfw-umd-forest-api/app
