develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35737:35729"
  container_name: gfw-umd-forest-api-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URI: http://192.168.99.100:8000
    CARTODB_APIKEY: <apikey>
    CARTODB_USER: <user>
    SELF_REGISTRY: "on"
    KEYMETRICS_PRIVATEKEY: <private>
    KEYMETRICS_PUBLICKEY: <public>
  command: develop
  volumes:
    - ./app:/opt/gfw-umd-forest-api/app
