develop:
  build: .
  ports:
    - "3603:3603"
  container_name: gfw-umd-forest-api-develop
  environment:
    PORT: 3603
    NODE_ENV: dev
    NODE_PATH: app/src
    ENVIRONMENT: dev
    DEBUG: "True"
    CT_URL: http://mymachine:9000
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    LOCAL_URL: http://mymachine:3603
    API_GATEWAY_URL: http://mymachine:9000
    EE_PRIVATE_KEY: ${EE_PRIVATE_KEY}
    CARTODB_USER: ${CARTODB_USER}
    API_VERSION: v1
    CT_REGISTER_MODE: auto
    FASTLY_ENABLED: "false"
  command: develop
  volumes:
    - ./app:/opt/gfw-umd-forest-api/app
