version: "3"
services:
  test:
    build: .
    container_name: gfw-umd-forest-api-test
    environment:
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      CT_REGISTER_MODE: auto
    command: test
