develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35737:35729"
  container_name: gfw-umd-forest-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_USER: <data>
    EE_PRIVATE_KEY: <data>
    API_GATEWAY_URL: http://192.168.99.100:8000
  command: develop
  volumes:
    - ./app:/opt/gfw-umd-forest-api/app
