prod:
  image: vizzuality/gfw-umd-forest-api:1.0.1${STAGING}
  ports:
    - "3600"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-umd-forest-api${STAGING}
