develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35737:35729"
  container_name: gfw-umd-forest-api-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URI: http://192.168.99.100:8000
    CARTODB_APIKEY: 0e5365cb1a299778e9df9c7bf6db489af8aa08e1
    CARTODB_USER: wri-01
    SELF_REGISTRY: "on"
  command: develop
  volumes:
    - ./app:/opt/gfw-umd-forest-api/app
